# Generated by Django 4.1.2 on 2022-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features_sales_preduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TV', models.CharField(blank=True, max_length=255, null=True)),
                ('Radio', models.CharField(blank=True, max_length=255, null=True)),
                ('Newspaper', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
