# Generated by Django 4.1.2 on 2022-10-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_remove_features_sales_preduction_sales_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Predict', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
